### PR TITLE
No misleading links in contributing.md

### PR DESCRIPTION
**Pull request by FoksVHox**
Contributing had a 404 link in it. Now this is changed to https://discord.gg/gmod

### CODE REVIEW

**Comment by Kefta** [comment]
Please add that they should use the #help or #developer-general channels.

**Comment by FoksVHox** [comment]
That is hereby done.

**Comment by robotboy655** [comment]
Should do that to the `contributing.md` file you originally edited too. Links to http://support.facepunchstudios.com/ would also probably be a good idea.

**Comment by FoksVHox** [comment]
> Should do that to the `contributing.md` file you originally edited too.
What you mean by that @robotboy655 ? And I agree with that https://support.facepunchstudios.com/  should be in it aswell

**Pull request merged**
